const ORDER_STATUS_ALL = 0;
const ORDER_STATUS_WILL_PAY = 1;
const ORDER_STATUS_WILL_DELIVERY = 2;
const ORDER_STATUS_WILL_TAKE_DELIVERY = 3;
const ORDER_STATUS_FINISH = 4;

const ORDER_STATUS_TIP = ['','等待买家付款','等待卖家发货','卖家已发货','交易成功']
const ORDER_STATUS_ZH = ['','待支付','待发货','待收货','已完成']

export {
    ORDER_STATUS_ALL,
    ORDER_STATUS_WILL_PAY,
    ORDER_STATUS_WILL_DELIVERY,
    ORDER_STATUS_WILL_TAKE_DELIVERY,
    ORDER_STATUS_FINISH,
    ORDER_STATUS_TIP,
    ORDER_STATUS_ZH
}